name: Continuous Integration

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

jobs:
    build:
        name: Build + Prettier
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
            - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
              with:
                  version: 10
                  run_install: false
            - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
              with:
                  node-version: 22
                  cache: "pnpm"
            - run: pnpm install --frozen-lockfile
            - run: pnpm prisma generate
            - run: pnpm build
            - run: pnpm format:check
